#!/usr/bin/env bash
###############################################################################
# gParaKV Throughput Benchmark                                                #
#                                                                             #
# This script benchmarks gParaKV write throughput (fillrandom) and read       #
# throughput (readrandom). Results are reported by RocksDB’s `db_bench` in    #
# MB/s.                                                                       #
#                                                                             #
# PARAMETER MEANINGS                                                          #
#   VALUE_SIZE : Value size in **bytes**.                                      #
#   KEY_SIZE   : Key size in **bytes** (fixed at 16 B).                        #
#   NUM_KV     : Number of key–value pairs to generate.                       #
#   DB_PATH    : Directory where the database (SSTables) will be created.     #
#                                                                             #
# DATA-SET SIZE                                                               #
#   Approximate bytes written ≈ ((VALUE_SIZE + KEY_SIZE) * NUM_KV) >> 30.     #
#   With the defaults below, the load is ≈ 100 GiB.                           #
#   Modify VALUE_SIZE or NUM_KV to scale the workload.                        #
###############################################################################

# --- Configurable variables --------------------------------------------------
VALUE_SIZE=1024          # bytes per value
KEY_SIZE=16              # bytes per key (constant)
NUM_KV=100000000         # total KV pairs
DB_PATH="/tmp/test"      # target directory for SSTables
OUT_FILE="benchmark.log" # file to capture stdout & stderr
# --------------------------------------------------------------------------- #

./build/db_bench \
    --benchmarks=fillrandom,readrandom \
    --value_size="${VALUE_SIZE}" \
    --num="${NUM_KV}" \
    --db="${DB_PATH}" \
    &> "${OUT_FILE}"
